version: '3'
services:
  mlflow:    
    image: "mlflow-server:latest"
    ports:
      - "5000:5000"
  jupyter:
    environment:
      - JUPYTER_ENABLE_LAB=yes  
    image: "jupyter-mlflow:latest"
    ports:
      - "8888:8888"
  portainer:    
    image: "portainer/portainer:1.23.0"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "9000:9000"
      - "8000:8000"
